[package]
name = "bandit_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "bandit_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
simdutf8 = { version = "0.1.4", features = ["aarch64_neon"] }
